import { NextRequest, NextResponse } from 'next/server';
import { GoogleGenAI, Type } from '@google/genai';

interface AnalyzeRequestBody {
  signalData: {
    symbol: string;
    signal: 'BUY' | 'SELL';
    price: number;
    spreadPips: number;
    lotSize: number;
    stopLoss?: number;
    takeProfit?: number;
    indicators?: {
      fastEma: number;
      slowEma: number;
      rsi: number;
      atr: number;
      currentSpreadPips?: number;
    };
    riskReason?: string;
  };
  marketMetrics?: {
    balance?: number;
    equity?: number;
    todayPnlPercent?: number;
    marginUsed?: number;
  };
  apiKey?: string;
}

export async function POST(req: NextRequest) {
  try {
    const body: AnalyzeRequestBody = await req.json();
    const { signalData, marketMetrics, apiKey: clientApiKey } = body;

    if (!signalData || !signalData.symbol || !signalData.signal) {
      return NextResponse.json(
        { error: 'Missing required signalData (symbol and signal are mandatory)' },
        { status: 400 }
      );
    }

    const apiKey = clientApiKey?.trim() || process.env.GEMINI_API_KEY?.trim();

    // If no valid Gemini API key is configured anywhere, automatically fall back to executing trades
    // based strictly on the Hardcoded Rule Engine with the required warning badge.
    if (!apiKey || apiKey === 'MY_GEMINI_API_KEY') {
      return NextResponse.json({
        approved: true,
        confidenceScore: 100,
        marketRegime: 'AI Offline - Enforcing Hardcoded Rules Only',
        reasoning:
          'AI Offline - Enforcing Hardcoded Rules Only: Gemini API key is missing or unconfigured. Executing trade strictly via RuleEngine parameters.',
        adjustedLotSizeMultiplier: 1.0,
        isAiOffline: true,
        warningBadge: 'AI Offline - Enforcing Hardcoded Rules Only',
        source: 'rule-engine-hardcoded',
      });
    }

    const ai = new GoogleGenAI({
      apiKey,
      httpOptions: {
        headers: {
          'User-Agent': 'aistudio-build',
        },
      },
    });

    const userPrompt = `
Evaluate the following trade setup generated by the Quantitative Rule Engine:
Symbol: ${signalData.symbol}
Signal Direction: ${signalData.signal}
Current Market Price: ${signalData.price}
Spread (pips): ${signalData.spreadPips}
Proposed Lot Size: ${signalData.lotSize}
Proposed Stop Loss: ${signalData.stopLoss ?? 'N/A'}
Proposed Take Profit: ${signalData.takeProfit ?? 'N/A'}

Technical Indicators:
- Fast EMA (${signalData.indicators?.fastEma ?? 'N/A'}) vs Slow EMA (${signalData.indicators?.slowEma ?? 'N/A'})
- RSI (14-period): ${signalData.indicators?.rsi ?? 'N/A'}
- ATR Volatility: ${signalData.indicators?.atr ?? 'N/A'}
- Spread vs Threshold: ${signalData.spreadPips} pips

Account Risk Metrics:
- Account Equity: $${marketMetrics?.equity ?? 10000}
- Daily P&L%: ${marketMetrics?.todayPnlPercent ?? 0}%
- Margin Used: $${marketMetrics?.marginUsed ?? 0}

Evaluate this against your Veto Criteria and approve or reject the trade. Output structured JSON adhering to the response schema.
`.trim();

    const response = await ai.models.generateContent({
      model: 'gemini-3.8-flash',
      contents: userPrompt,
      config: {
        systemInstruction: `You are a Conservative Algorithmic Risk Analyst & Trade Overseer for an institutional MetaTrader quantitative execution system.
Your primary duty is to strictly evaluate, approve, or veto trade setups generated by the hardcoded Rule Engine before market execution.
VETO CRITERIA:
1. Choppy / Ranging Conditions: If EMA fast and EMA slow are flat, entwined, or oscillating sideways during a trend setup, VETO the trade (approved: false).
2. Volatility / Spread Anomalies: If current spread is excessive relative to ATR or if RSI shows extreme exhaustion/divergence (e.g., buying into overbought RSI > 72 or selling into oversold RSI < 28), VETO or severely penalize confidence.
3. Multi-timeframe / Indicator Conflict: If indicators give mixed or contradictory signals, prioritize capital preservation and VETO.
APPROVAL CRITERIA:
1. Clean directional momentum with healthy EMA separation and supportive RSI momentum (e.g., RSI between 45-65 for BUY, 35-55 for SELL).
2. Favorable spread and stable ATR volatility.
When approved, provide an adjustedLotSizeMultiplier between 0.5 and 1.25 (default 1.0). If vetoed, set approved: false and adjustedLotSizeMultiplier to 0.0. Provide crisp, professional reasoning explaining your verdict.`,
        responseMimeType: 'application/json',
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            approved: {
              type: Type.BOOLEAN,
              description: 'Whether the trade is approved or vetoed by the risk analyst.',
            },
            confidenceScore: {
              type: Type.INTEGER,
              description: 'Confidence score between 0 and 100 in the trade setup.',
            },
            marketRegime: {
              type: Type.STRING,
              description:
                "Current market regime description, e.g., 'Trending Up / High Volatility', 'Choppy / Ranging', 'Bullish Trend / Low Risk', 'Bearish Breakdown / High Volatility'.",
            },
            reasoning: {
              type: Type.STRING,
              description: 'Detailed professional reasoning justifying the approval or veto decision.',
            },
            adjustedLotSizeMultiplier: {
              type: Type.NUMBER,
              description: 'Multiplier between 0.0 and 1.5 to scale position size based on regime conviction.',
            },
          },
          required: [
            'approved',
            'confidenceScore',
            'marketRegime',
            'reasoning',
            'adjustedLotSizeMultiplier',
          ],
        },
      },
    });

    const rawText = response.text?.trim() || '';
    if (!rawText) {
      throw new Error('Empty response received from Gemini API');
    }

    const parsedJson = JSON.parse(rawText);

    return NextResponse.json({
      approved: Boolean(parsedJson.approved),
      confidenceScore: Math.min(100, Math.max(0, Number(parsedJson.confidenceScore) || 50)),
      marketRegime: String(parsedJson.marketRegime || 'Neutral / Evaluating'),
      reasoning: String(parsedJson.reasoning || 'AI evaluation complete.'),
      adjustedLotSizeMultiplier: Number(parsedJson.adjustedLotSizeMultiplier ?? 1.0),
      isAiOffline: false,
      warningBadge: null,
      source: 'gemini-3.8-flash',
    });
  } catch (err: any) {
    console.error('[API /api/gemini/analyze Error]:', err);
    // API Key Guard: If key is invalid or API call fails, fall back to Hardcoded Rule Engine
    return NextResponse.json({
      approved: true,
      confidenceScore: 100,
      marketRegime: 'AI Offline - Enforcing Hardcoded Rules Only',
      reasoning: `AI Offline - Enforcing Hardcoded Rules Only: ${err?.message || 'Gemini API key is invalid or unavailable'}. Trade validated and executed strictly via RuleEngine parameters.`,
      adjustedLotSizeMultiplier: 1.0,
      isAiOffline: true,
      warningBadge: 'AI Offline - Enforcing Hardcoded Rules Only',
      source: 'rule-engine-hardcoded',
    });
  }
}

function generateDeterministicFallback(
  signalData: any,
  marketMetrics?: any,
  isApiError: boolean = false,
  errorMsg?: string
) {
  const indicators = signalData.indicators || {
    fastEma: signalData.price * 1.0005,
    slowEma: signalData.price * 0.9995,
    rsi: 54,
    atr: 0.0012,
  };

  const emaDelta = (indicators.fastEma - indicators.slowEma) / (indicators.slowEma || 1);
  const rsi = indicators.rsi ?? 50;
  const isBuy = signalData.signal === 'BUY';

  let approved = true;
  let confidenceScore = 82;
  let marketRegime = isBuy ? 'Bullish Trend / Low Risk' : 'Bearish Momentum / Low Risk';
  let reasoning = '';
  let adjustedLotSizeMultiplier = 1.0;

  // Check chop / ranging conditions
  if (Math.abs(emaDelta) < 0.00005) {
    approved = false;
    confidenceScore = 42;
    marketRegime = 'Choppy / Ranging';
    reasoning = `Vetoed: Fast EMA (${indicators.fastEma.toFixed(5)}) and Slow EMA (${indicators.slowEma.toFixed(5)}) are entwined. Market is ranging sideways with inadequate trend structure.`;
    adjustedLotSizeMultiplier = 0.0;
  } else if (isBuy && rsi > 70) {
    approved = false;
    confidenceScore = 48;
    marketRegime = 'Overbought / Exhaustion Risk';
    reasoning = `Vetoed: RSI is overbought (${rsi.toFixed(1)} > 70.0). High risk of immediate mean-reversion pullback.`;
    adjustedLotSizeMultiplier = 0.0;
  } else if (!isBuy && rsi < 30) {
    approved = false;
    confidenceScore = 46;
    marketRegime = 'Oversold / Exhaustion Risk';
    reasoning = `Vetoed: RSI is oversold (${rsi.toFixed(1)} < 30.0). Short entry rejected due to stretched momentum and reversal risk.`;
    adjustedLotSizeMultiplier = 0.0;
  } else {
    approved = true;
    confidenceScore = isBuy ? (rsi > 50 ? 86 : 74) : (rsi < 50 ? 84 : 72);
    marketRegime = isBuy ? 'Bullish Trend / Low Risk' : 'Bearish Trend / Moderate Risk';
    reasoning = isBuy
      ? `Approved: Technical EMA crossover aligns with bullish momentum. Fast EMA (${indicators.fastEma.toFixed(5)}) expands cleanly above Slow EMA with supportive RSI (${rsi.toFixed(1)}).`
      : `Approved: Bearish momentum verified. Fast EMA (${indicators.fastEma.toFixed(5)}) tracks below Slow EMA with downward slope and healthy RSI headroom (${rsi.toFixed(1)}).`;
    adjustedLotSizeMultiplier = confidenceScore > 80 ? 1.0 : 0.8;
  }

  if (isApiError && errorMsg) {
    reasoning += ` (Note: Algorithmic risk model fallback engaged: ${errorMsg})`;
  }

  return {
    approved,
    confidenceScore,
    marketRegime,
    reasoning,
    adjustedLotSizeMultiplier,
    source: isApiError ? 'algorithmic-fallback' : 'local-overseer',
  };
}
