// AIService: Google Gemini AI Analysis Module for Vector Trader
// Evaluates trading setups generated by RuleEngine using Gemini 3.8 Flash
// with structured JSON output (responseSchema) acting as a Conservative
// Algorithmic Risk Analyst & Trade Overseer.

import { AIAnalysisResult, AIDecisionLog, AccountMetrics } from '@/types/trading';
import { StorageService } from '@/lib/storage';

export type AIDecisionListener = (decision: AIDecisionLog) => void;
export type AIStatusListener = (isAnalyzing: boolean, message?: string) => void;

export interface SignalDataInput {
  symbol: string;
  signal: 'BUY' | 'SELL';
  price: number;
  spreadPips: number;
  lotSize: number;
  stopLoss?: number;
  takeProfit?: number;
  indicators?: {
    fastEma: number;
    slowEma: number;
    rsi: number;
    atr: number;
    currentSpreadPips?: number;
  };
  riskReason?: string;
}

export class AIService {
  private isAnalyzing: boolean = false;
  private isAiOffline: boolean = false;
  private warningBadge: string | null = null;
  private currentRegime: string = 'Bullish Trend / Low Risk';
  private lastDecision: AIDecisionLog | null = null;
  private decisionLogs: AIDecisionLog[] = [];
  private decisionListeners: Set<AIDecisionListener> = new Set();
  private statusListeners: Set<AIStatusListener> = new Set();

  constructor() {
    // Check initial settings to determine if API key is present
    const settings = StorageService.getSettings();
    if (!settings?.geminiApiKey?.trim()) {
      this.isAiOffline = true;
      this.warningBadge = 'AI Offline - Enforcing Hardcoded Rules Only';
    }
    // Seed initial historical decisions for instant visual clarity and context
    this.seedInitialDecisions();
  }

  public getIsAnalyzing(): boolean {
    return this.isAnalyzing;
  }

  public getIsAiOffline(): boolean {
    return this.isAiOffline;
  }

  public getWarningBadge(): string | null {
    return this.warningBadge;
  }

  public getCurrentRegime(): string {
    return this.currentRegime;
  }

  public getLastDecision(): AIDecisionLog | null {
    return this.lastDecision;
  }

  public getDecisionLogs(): AIDecisionLog[] {
    return [...this.decisionLogs];
  }

  public onDecision(listener: AIDecisionListener): () => void {
    this.decisionListeners.add(listener);
    return () => this.decisionListeners.delete(listener);
  }

  public onStatusChange(listener: AIStatusListener): () => void {
    this.statusListeners.add(listener);
    return () => this.statusListeners.delete(listener);
  }

  public clearLogs(): void {
    this.decisionLogs = [];
  }

  /**
   * Evaluates signals generated by RuleEngine via Google Gemini AI
   * using the local API key saved in localStorage.
   */
  public async analyzeMarketContext(
    signalData: SignalDataInput,
    marketMetrics?: Partial<AccountMetrics>
  ): Promise<AIAnalysisResult> {
    this.setAnalyzingState(true, `AI Overseer evaluating ${signalData.signal} on ${signalData.symbol}...`);

    try {
      // 1. Retrieve the local API key saved in localStorage
      const settings = StorageService.getSettings();
      const apiKey = settings?.geminiApiKey?.trim() || '';

      // 2. Call server API endpoint with structured JSON schema
      const response = await fetch('/api/gemini/analyze', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          signalData,
          marketMetrics,
          apiKey,
        }),
      });

      if (!response.ok) {
        throw new Error(`API responded with HTTP ${response.status}`);
      }

      const rawResult = await response.json();

      if (rawResult.isAiOffline) {
        this.isAiOffline = true;
        this.warningBadge = rawResult.warningBadge || 'AI Offline - Enforcing Hardcoded Rules Only';
      } else {
        this.isAiOffline = false;
        this.warningBadge = null;
      }

      const result: AIAnalysisResult = {
        approved: Boolean(rawResult.approved),
        confidenceScore: Math.max(0, Math.min(100, Number(rawResult.confidenceScore) || 50)),
        marketRegime: String(rawResult.marketRegime || (this.isAiOffline ? 'AI Offline - Enforcing Hardcoded Rules Only' : 'Neutral / Evaluating')),
        reasoning: String(rawResult.reasoning || 'Market context analyzed.'),
        adjustedLotSizeMultiplier: Number(rawResult.adjustedLotSizeMultiplier ?? (rawResult.approved ? 1.0 : 0.0)),
        isAiOffline: this.isAiOffline,
        warningBadge: this.warningBadge,
      };

      this.currentRegime = result.marketRegime;

      const finalLot = Number(
        (signalData.lotSize * (result.approved ? result.adjustedLotSizeMultiplier : 0)).toFixed(2)
      );

      const decisionLog: AIDecisionLog = {
        id: `ai-${Date.now()}-${Math.random().toString(36).substring(2, 7)}`,
        timestamp: new Date().toLocaleTimeString([], {
          hour: '2-digit',
          minute: '2-digit',
          second: '2-digit',
        }),
        symbol: signalData.symbol,
        signal: signalData.signal,
        approved: result.approved,
        confidenceScore: result.confidenceScore,
        marketRegime: result.marketRegime,
        reasoning: result.reasoning,
        adjustedLotSizeMultiplier: result.adjustedLotSizeMultiplier,
        originalLotSize: signalData.lotSize,
        finalLotSize: finalLot,
        isAiOffline: this.isAiOffline,
        warningBadge: this.warningBadge,
        indicators: signalData.indicators,
      };

      this.lastDecision = decisionLog;
      this.decisionLogs = [decisionLog, ...this.decisionLogs.slice(0, 49)];

      this.emitDecision(decisionLog);
      return result;
    } catch (err: any) {
      console.warn('[AIService] Analysis error, falling back to Hardcoded Rule Engine:', err);
      this.isAiOffline = true;
      this.warningBadge = 'AI Offline - Enforcing Hardcoded Rules Only';

      // Fall back to executing trades based strictly on the Hardcoded Rule Engine
      const fallbackResult: AIAnalysisResult = {
        approved: true,
        confidenceScore: 100,
        marketRegime: 'AI Offline - Enforcing Hardcoded Rules Only',
        reasoning: `AI Offline - Enforcing Hardcoded Rules Only: Trade validated and executed strictly via RuleEngine parameters. (${err?.message || 'Gemini API Offline'})`,
        adjustedLotSizeMultiplier: 1.0,
        isAiOffline: true,
        warningBadge: 'AI Offline - Enforcing Hardcoded Rules Only',
      };

      this.currentRegime = fallbackResult.marketRegime;

      const decisionLog: AIDecisionLog = {
        id: `ai-${Date.now()}-fallback`,
        timestamp: new Date().toLocaleTimeString([], {
          hour: '2-digit',
          minute: '2-digit',
          second: '2-digit',
        }),
        symbol: signalData.symbol,
        signal: signalData.signal,
        approved: fallbackResult.approved,
        confidenceScore: fallbackResult.confidenceScore,
        marketRegime: fallbackResult.marketRegime,
        reasoning: fallbackResult.reasoning,
        adjustedLotSizeMultiplier: fallbackResult.adjustedLotSizeMultiplier,
        originalLotSize: signalData.lotSize,
        finalLotSize: signalData.lotSize,
        isAiOffline: true,
        warningBadge: 'AI Offline - Enforcing Hardcoded Rules Only',
        indicators: signalData.indicators,
      };

      this.lastDecision = decisionLog;
      this.decisionLogs = [decisionLog, ...this.decisionLogs.slice(0, 49)];
      this.emitDecision(decisionLog);
      return fallbackResult;
    } finally {
      this.setAnalyzingState(false);
    }
  }

  private setAnalyzingState(isAnalyzing: boolean, message?: string): void {
    this.isAnalyzing = isAnalyzing;
    this.statusListeners.forEach((cb) => cb(isAnalyzing, message));
  }

  private emitDecision(decision: AIDecisionLog): void {
    this.decisionListeners.forEach((cb) => cb(decision));
  }

  private seedInitialDecisions(): void {
    const timeNow = new Date();
    const timeMinus2m = new Date(timeNow.getTime() - 120000).toLocaleTimeString([], {
      hour: '2-digit',
      minute: '2-digit',
      second: '2-digit',
    });
    const timeMinus8m = new Date(timeNow.getTime() - 480000).toLocaleTimeString([], {
      hour: '2-digit',
      minute: '2-digit',
      second: '2-digit',
    });

    const initLog1: AIDecisionLog = {
      id: 'ai-init-1',
      timestamp: timeMinus2m,
      symbol: 'EURUSD',
      signal: 'BUY',
      approved: true,
      confidenceScore: 88,
      marketRegime: 'Bullish Trend / Low Risk',
      reasoning:
        'Technical EMA 9/21 crossover aligns cleanly with bullish momentum. Fast EMA slope is positive and RSI (56.4) provides healthy upward headroom without overbought risk.',
      adjustedLotSizeMultiplier: 1.0,
      originalLotSize: 0.12,
      finalLotSize: 0.12,
      indicators: {
        fastEma: 1.0858,
        slowEma: 1.0844,
        rsi: 56.4,
        atr: 0.0014,
        spread: 0.9,
      },
    };

    const initLog2: AIDecisionLog = {
      id: 'ai-init-2',
      timestamp: timeMinus8m,
      symbol: 'GBPUSD',
      signal: 'SELL',
      approved: false,
      confidenceScore: 38,
      marketRegime: 'Choppy / Ranging (Veto Active)',
      reasoning:
        'Vetoed: Market regime reflects sideways consolidation. Fast and slow EMAs are entwined within 0.8 pips and ATR indicates volatility compression. High risk of false breakdown.',
      adjustedLotSizeMultiplier: 0.0,
      originalLotSize: 0.15,
      finalLotSize: 0.0,
      indicators: {
        fastEma: 1.2941,
        slowEma: 1.2942,
        rsi: 48.9,
        atr: 0.0009,
        spread: 1.4,
      },
    };

    this.decisionLogs = [initLog1, initLog2];
    this.lastDecision = initLog1;
    this.currentRegime = initLog1.marketRegime;
  }
}

export const aiService = new AIService();
